### ISSUE TITLE
[Question] Expected output for IOCTL_BIOMETRIC_CONNECT_SECURE

### ISSUE THREAD

**Issue by pbesson-invn** [Microsoft/SecureDeviceConnectionProtocol#11]
Hello,

The SDCP wiki documentation indicates `IOCTL_BIOMETRIC_CONNECT_SECURE `will be added to WBF and the expected output is `WINBIO_SECURE_CONNECTION_RESPONSE` which nests `WINBIO_SECURE_CONNECTION_DATA`.

However, after updating WDK and looking at the updated winbio headers for RS4, there is no structure `WINBIO_SECURE_CONNECTION_RESPONSE` defined.

So, what does the framework really expects? `WINBIO_SECURE_CONNECTION_RESPONSE` or `WINBIO_SECURE_CONNECTION_DATA`?

If the later, as there is no `WinBioHresult` field, how to report a failure in case the request to the device was unsuccessful?

Thank you!

Regards,
Paul

**Comment by pbesson-invn** [comment]
Sharing my findings for other.

Default SensorAdapter in RS4/RS5 does not seems to implement `SensorAdapterConnectSecure()`, hence  
`IOCTL_BIOMETRIC_CONNECT_SECURE` payload could be pretty much anything as long as SensorAdapterConnectSecure() returns `WINBIO_SECURE_CONNECTION_DATA`.

**Comment by jdtw** [comment]
@pbesson-invn sorry for the radio silence! You're correct that the inbox sensor adapter does not support the new `IOCTL` yet, since the inbox adapter only supports basic sensors, not advanced sensors. We expect you to write your own sensor adapter here, in which case you just need to support the `SensorAdapterConnectSecure` function, and are free to use your own `IOCTL` (or whatever) to talk to your hardware.
